<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Webhooks;


class StockUpdateRequestBody
{
	#[\JMS\Serializer\Annotation\SerializedName('drink')]
    #[\JMS\Serializer\Annotation\Type('OpenAPI\OpenAPI\Models\Components\DrinkInput')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\OpenAPI\OpenAPI\Models\Components\DrinkInput $drink = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('ingredient')]
    #[\JMS\Serializer\Annotation\Type('OpenAPI\OpenAPI\Models\Components\IngredientInput')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\OpenAPI\OpenAPI\Models\Components\IngredientInput $ingredient = null;
    
	public function __construct()
	{
		$this->drink = null;
		$this->ingredient = null;
	}
}
