<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Callbacks;


class CreateOrderOrderUpdateRequestBody
{
    /**
     * An order for a drink or ingredient.
     * 
     * @var ?\OpenAPI\OpenAPI\Models\Components\OrderInput $order
     */
	#[\JMS\Serializer\Annotation\SerializedName('order')]
    #[\JMS\Serializer\Annotation\Type('OpenAPI\OpenAPI\Models\Components\OrderInput')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\OpenAPI\OpenAPI\Models\Components\OrderInput $order = null;
    
	public function __construct()
	{
		$this->order = null;
	}
}
