<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;

use \OpenAPI\OpenAPI\Utils\SpeakeasyMetadata;
class CreateOrderRequest
{
    /**
     * $requestBody
     * 
     * @var array<\OpenAPI\OpenAPI\Models\Components\OrderInput> $requestBody
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public array $requestBody;
    
    /**
     * The url to call when the order is updated.
     * 
     * @var ?string $callbackUrl
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=callback_url')]
    public ?string $callbackUrl = null;
    
	public function __construct()
	{
		$this->requestBody = [];
		$this->callbackUrl = null;
	}
}
