<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;

use \OpenAPI\OpenAPI\Utils\SpeakeasyMetadata;
class ListIngredientsRequest
{
    /**
     * A list of ingredients to filter by. If not provided all ingredients will be returned.
     * 
     * @var ?array<string> $ingredients
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=false,name=ingredients')]
    public ?array $ingredients = null;
    
	public function __construct()
	{
		$this->ingredients = null;
	}
}
