<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;

use \OpenAPI\OpenAPI\Utils\SpeakeasyMetadata;
class ListDrinksRequest
{
    /**
     * The type of drink to filter by. If not provided all drinks will be returned.
     * 
     * @var ?\OpenAPI\OpenAPI\Models\Components\DrinkType $drinkType
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=drinkType')]
    public ?\OpenAPI\OpenAPI\Models\Components\DrinkType $drinkType = null;
    
	public function __construct()
	{
		$this->drinkType = null;
	}
}
