<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


/**
 * LoginResponseBody - The api key to use for authenticated endpoints.
 * 
 * @package OpenAPI\OpenAPI\Models\Operations
 * @access public
 */
class LoginResponseBody
{
	#[\JMS\Serializer\Annotation\SerializedName('token')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $token = null;
    
	public function __construct()
	{
		$this->token = null;
	}
}
