<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


class LoginRequestBody
{
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<OpenAPI\OpenAPI\Models\Operations\Type>')]
    public Type $type;
    
	public function __construct()
	{
		$this->type = \OpenAPI\OpenAPI\Models\Operations\Type::ApiKey;
	}
}
