<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


class RequestBody
{
	#[\JMS\Serializer\Annotation\SerializedName('url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $url = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('webhook')]
    #[\JMS\Serializer\Annotation\Type('enum<OpenAPI\OpenAPI\Models\Operations\Webhook>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Webhook $webhook = null;
    
	public function __construct()
	{
		$this->url = null;
		$this->webhook = null;
	}
}
