<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


enum Type: string
{
    case ApiKey = 'apiKey';
    case Jwt = 'JWT';
}
