<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


class BadRequest
{
    /**
     * Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)
     * 
     * @var ?string $error
     */
	#[\JMS\Serializer\Annotation\SerializedName('error')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $error = null;
    
    /**
     * HTTP status code
     * 
     * @var ?float $statusCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('status_code')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $statusCode = null;
    
    /**
     * The type of error returned
     * 
     * @var ?string $typeName
     */
	#[\JMS\Serializer\Annotation\SerializedName('type_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $typeName = null;
    
	public function __construct()
	{
		$this->error = null;
		$this->statusCode = null;
		$this->typeName = null;
	}
}
