<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


class DrinkInput
{
    /**
     * The name of the drink.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The price of one unit of the drink in US cents.
     * 
     * @var float $price
     */
	#[\JMS\Serializer\Annotation\SerializedName('price')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $price;
    
    /**
     * The product code of the drink, only available when authenticated.
     * 
     * @var ?string $productCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('productCode')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $productCode = null;
    
    /**
     * The type of drink.
     * 
     * @var ?\OpenAPI\OpenAPI\Models\Components\DrinkType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<OpenAPI\OpenAPI\Models\Components\DrinkType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?DrinkType $type = null;
    
	public function __construct()
	{
		$this->name = "";
		$this->price = 0;
		$this->productCode = null;
		$this->type = null;
	}
}
