<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


/** The type of drink. */
enum DrinkType: string
{
    case Cocktail = 'cocktail';
    case NonAlcoholic = 'non-alcoholic';
    case Beer = 'beer';
    case Wine = 'wine';
    case Spirit = 'spirit';
    case Other = 'other';
}
