<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


/** The type of ingredient. */
enum IngredientType: string
{
    case Fresh = 'fresh';
    case LongLife = 'long-life';
    case Packaged = 'packaged';
}
