<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


class IngredientInput
{
    /**
     * The name of the ingredient.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The product code of the ingredient, only available when authenticated.
     * 
     * @var ?string $productCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('productCode')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $productCode = null;
    
    /**
     * The type of ingredient.
     * 
     * @var \OpenAPI\OpenAPI\Models\Components\IngredientType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<OpenAPI\OpenAPI\Models\Components\IngredientType>')]
    public IngredientType $type;
    
	public function __construct()
	{
		$this->name = "";
		$this->productCode = null;
		$this->type = \OpenAPI\OpenAPI\Models\Components\IngredientType::Fresh;
	}
}
