<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


/** The type of order. */
enum OrderType: string
{
    case Drink = 'drink';
    case Ingredient = 'ingredient';
}
