<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


/** The status of the order. */
enum Status: string
{
    case Pending = 'pending';
    case Processing = 'processing';
    case Complete = 'complete';
}
