<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI;

/** The environment name. Defaults to the production environment. */
enum ServerEnvironment: string
{
    case Prod = 'prod';
    case Staging = 'staging';
    case Dev = 'dev';
}
