<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */


declare(strict_types=1);

namespace OpenAPI\OpenAPI;

/**
 * SpeakeasyBuilder is used to configure and build an instance of the SDK.
 * 
 * @package OpenAPI\OpenAPI
 */
class SpeakeasyBuilder
{
    private SDKConfiguration $sdkConfig;

    public function __construct() {
        $this->sdkConfig = new SDKConfiguration();
    }

    /**
     * setClient allows setting a custom Guzzle client for the SDK to make requests with.
     *
     * @param \GuzzleHttp\ClientInterface $client
     * @return SpeakeasyBuilder
     */
    public function setClient(\GuzzleHttp\ClientInterface $client): SpeakeasyBuilder
    {
        $this->sdkConfig->defaultClient = $client;
        return $this;
    }
    
    /**
     * setSecurity is used to configure the security required for the SDK.
     *
     * @param Models\Components\Security $security
     * @return SpeakeasyBuilder
     */
    public function setSecurity(Models\Components\Security $security): SpeakeasyBuilder
    {
        $this->sdkConfig->security = $security;
        return $this;
    }
    
    /**
     * setServerUrl is used to configure the server URL for the SDK, and optionally template any parameters in the URL.
     *
     * @param string $serverUrl
     * @param array<string, string> $params
     * @return SpeakeasyBuilder
     */
    public function setServerUrl(string $serverUrl, ?array $params = null): SpeakeasyBuilder
    {
        $this->sdkConfig->serverUrl = Utils\Utils::templateUrl($serverUrl, $params);
        return $this;
    }
    
    /**
     * setServer is used to configure the server for the SDK
     *
     * @param string $server
     * @return SpeakeasyBuilder
     */
    public function setServer(string $server): SpeakeasyBuilder
    {
        $this->sdkConfig->server = $server;
        return $this;
    }
    
    
    /**
     * setEnvironment is used to configure the environment variable for url substitution
     *
     * @param ServerEnvironment $environment
     * @return SpeakeasyBuilder
     */
    public function setEnvironment(ServerEnvironment $environment): SpeakeasyBuilder
    {
        foreach ($this->sdkConfig->serverDefaults as $server => $serverDefaults) {
            if (!array_key_exists('environment', $serverDefaults)) {
                continue;
            }
            
            $this->sdkConfig->serverDefaults[$server]['environment'] = $environment->value;
            
        }

        return $this;
    }
    /**
     * setOrganization is used to configure the organization variable for url substitution
     *
     * @param string $organization
     * @return SpeakeasyBuilder
     */
    public function setOrganization(string $organization): SpeakeasyBuilder
    {
        foreach ($this->sdkConfig->serverDefaults as $server => $serverDefaults) {
            if (!array_key_exists('organization', $serverDefaults)) {
                continue;
            }
            
            $this->sdkConfig->serverDefaults[$server]['organization'] = $organization;
        }

        return $this;
    }
    
    /**
     * build is used to build the SDK with any of the configured options.
     *
     * @return Speakeasy
     */
    public function build(): Speakeasy
    {
		if ($this->sdkConfig->defaultClient === null) {
			$this->sdkConfig->defaultClient = new \GuzzleHttp\Client([
				'timeout' => 60,
			]);
		}
		if ($this->sdkConfig->security !== null) {
			$this->sdkConfig->securityClient = Utils\Utils::configureSecurityClient($this->sdkConfig->defaultClient, $this->sdkConfig->security);
		}
		
		if ($this->sdkConfig->securityClient === null) {
			$this->sdkConfig->securityClient = $this->sdkConfig->defaultClient;
		}

        return new Speakeasy($this->sdkConfig);
    }
}